# Generated by Django 6.0.3 on 2026-04-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Primary Configuration', max_length=100)),
                ('short_code', models.CharField(default='174379', help_text='The M-Pesa Paybill or Till Number', max_length=50)),
                ('consumer_key', models.CharField(max_length=255)),
                ('consumer_secret', models.CharField(max_length=255)),
                ('passkey', models.TextField(help_text='Lipa Na M-Pesa Online Passkey')),
                ('is_sandbox', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'M-Pesa Configuration',
                'verbose_name_plural': 'M-Pesa Configurations',
            },
        ),
    ]
