# Generated by Django 6.0.3 on 2026-04-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='form_level',
            field=models.CharField(blank=True, default='Form 4', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
