# Generated by Django 6.0.3 on 2026-04-05 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('workbook', 'Workbook'), ('past_paper', 'Past Paper'), ('mock_exam', 'Mock Exam'), ('questions', 'Practice Questions')], default='workbook', max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('is_free', models.BooleanField(default=False)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='resources/pdfs/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='resources/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
